### ISSUE TITLE
부지평가 COC 리팩터링

### ISSUE THREAD

**Issue by innerstella** [VIRAPkoreauniv/RAPVI-2024#3]
### 설명

기존 코드 문제점
- useState로 값 관리
    - 너무 값이 많아 코드가 어지러움
        - 객체로 관리할까?
- localStorage에 값 저장
    - 페이지별로 값을 로컬 스토리지에 넣어뒀다가 씀
    - 필요할 때 key로 접근해서 사용하기 귀찮음
- selectChem 함수가 너무 길어 가독성 유지보수성 떨어짐
    - util 함수로 분리
        - param : selectedChem
        - return : value, default value
    - valueList, defaultValueList 데이터화 필요

### TODO

- [x] valueList, defaultValueList 데이터화
- [x] siteInput value coc로 객체 구조화
- [x] defaultValue 관리용 atom 추가
- [x] selectedChem 함수 util 함수로 분리
- [x] useState로 하나씩 관리되던 값들 객체화
    `{ coc: { S : 0, Hc : 0 } }`

- [x] recoil로 상태 관리
- [x] 기본 정보 입력 페이지에서 리코일 상태 초기화

**Comment by innerstella** [comment]
<img width="1710" alt="image" src="https://github.com/user-attachments/assets/06cbfb9d-9659-43f6-a027-ee4bd9277a9d">

180여종의 화학물질
